#!/usr/bin/env node
/**
 * build-fonts.js — 一次性脚本：从 @fontsource 包提取 woff2 字体到 assets/fonts，
 * 并生成 assets/css/fonts.css（仅 woff2，保留 unicode-range 分块按需加载）。
 *
 * 用法：node scripts/build-fonts.js
 * 产物提交进仓库；线上零依赖、零构建。
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const FONTS_DIR = path.join(ROOT, "assets", "fonts");
const OUT_CSS = path.join(ROOT, "assets", "css", "fonts.css");

// 需要的字体：包名 → 该包下要取的 css 文件列表
const WANTED = [
  { pkg: "noto-serif-sc", css: ["500.css", "700.css"] },
  { pkg: "newsreader", css: ["latin-400.css", "latin-400-italic.css", "latin-500.css", "latin-700.css"] },
  { pkg: "geist-mono", css: ["latin-400.css", "latin-500.css"] },
];

fs.rmSync(FONTS_DIR, { recursive: true, force: true });
fs.mkdirSync(FONTS_DIR, { recursive: true });

let out = [
  "/* ============================================================",
  "   fonts.css — 自托管字体（generated by scripts/build-fonts.js）",
  "   Noto Serif SC 500/700 · Newsreader · Geist Mono — 仅 woff2",
  "   ============================================================ */",
  "",
];
let copied = 0;

for (const { pkg, css } of WANTED) {
  const pkgDir = path.join(ROOT, "node_modules", "@fontsource", pkg);
  for (const cssFile of css) {
    const srcCss = fs.readFileSync(path.join(pkgDir, cssFile), "utf8");
    // 拆出每个 @font-face 块，丢掉 woff 回退，只留 woff2，并改写路径
    const blocks = srcCss.match(/@font-face\s*\{[^}]*\}/g) || [];
    for (const block of blocks) {
      const m = block.match(/url\(\.\/files\/([^)]+\.woff2)\)/);
      if (!m) continue;
      const file = m[1];
      fs.copyFileSync(path.join(pkgDir, "files", file), path.join(FONTS_DIR, file));
      copied++;
      const cleaned = block
        .replace(/src:\s*[^;]+;/, `src: url(/assets/fonts/${file}) format("woff2");`)
        .replace(/\n\s+/g, "\n  ");
      out.push(cleaned, "");
    }
  }
}

fs.writeFileSync(OUT_CSS, out.join("\n"));
const totalMB = fs.readdirSync(FONTS_DIR).reduce((s, f) => s + fs.statSync(path.join(FONTS_DIR, f)).size, 0) / 1048576;
console.log(`done: ${copied} woff2 → assets/fonts (${totalMB.toFixed(1)} MB), css → assets/css/fonts.css`);
